server:
  port: 8080
  servlet:
    session:
      timeout: 1800
spring:
  profiles:
    active: local
  config:
    import:
      - application-local.yaml
      - application-prod.yaml
      - application-release.yaml
      - application-dev.yaml

