server:
  port: 8080
  servlet:
    session:
      timeout: 1800
spring:
  profiles:
    active: dev
  config:
    import:
      - application-dev.yaml
      - application-prod.yaml
      - application-temp.yaml

