spring.config.activate.on-profile: develop

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_DATASOURCE_URL}
    username: ${MYSQL_DATASOURCE_USERNAME}
    password: ${MYSQL_DATASOURCE_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: mysql
    open-in-view: false
  data:
    redis:
      host: ${REDIS_DATASOURCE_HOST}
      port: ${REDIS_DATASOURCE_PORT}
  mail:
    host: ${DEV_MAIL_HOST}
    port: 587
    username: ${DEV_MAIL_USERNAME}
    password: ${DEV_MAIL_PASSWORD}
    from: ${DEV_MAIL_SENDER}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


cors:
  allowed-origins: https://dev.areyouhere.today, https://dev.www.areyouhere.today
cookie:
  encode: ${SECRET_KEY}

